image:
  file: .gitpod.Dockerfile

tasks:
  - init: |
      cmake --version
      python3 --version
      dtc --version
      west --version
  - command: |
      cd ~/zephyrproject/zephyr/samples/subsys/display/cfb
      mkdir build
      cd build
      cmake -DBOARD=native_posix_64 -GNinja ..
      ninja run

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-preview