image: gitpod/workspace-full-vnc

tasks:
  - init: |
      # https://docs.zephyrproject.org/latest/getting_started/index.html
      # Install dependencies
      sudo apt update
      cd ~
      wget https://apt.kitware.com/kitware-archive.sh
      sudo bash kitware-archive.sh
      sudo apt install -y --no-install-recommends git cmake ninja-build gperf \
        ccache dfu-util device-tree-compiler wget \
        python3-dev python3-pip python3-setuptools python3-tk python3-wheel xz-utils file \
        make gcc gcc-multilib g++-multilib libsdl2-dev
      cmake --version
      python3 --version
      dtc --version
  - init: |
      # Get Zephyr and install Python dependencies
      pip3 install --user -U west
      echo 'export PATH=~/.local/bin:"$PATH"' >> ~/.bashrc
      source ~/.bashrc
      west init ~/zephyrproject
      cd ~/zephyrproject
      west update
      west zephyr-export
      pip3 install --user -r ~/zephyrproject/zephyr/scripts/requirements.txt
      west --version
  - init: |
      # Install a Toolchain
      cd ~
      wget https://github.com/zephyrproject-rtos/sdk-ng/releases/download/v0.13.1/zephyr-sdk-0.13.1-linux-x86_64-setup.run
      chmod +x zephyr-sdk-0.13.1-linux-x86_64-setup.run
      ./zephyr-sdk-0.13.1-linux-x86_64-setup.run -- -d ~/zephyr-sdk-0.13.1
  - command: |
      cd ~/zephyrproject/zephyr/samples/subsys/display/cfb
      mkdir build
      cd build
      cmake -DBOARD=native_posix_64 -GNinja ..
      ninja run

ports:
  - port: 5900
    onOpen: ignore
  - port: 6080
    onOpen: open-browser